- hosts: 127.0.0.1
  connection: local
  become: true
  max_fail_percentage: 0

  tasks:
  - name: add and start for each hacluster nodes
    include_role:
      name: vbmc-start
    with_items: "{{ groups['hacluster_vbmc'] }}"
    loop_control:
      loop_var: nodename
    # always tag is to enable tags inside include_role
    #  https://github.com/ansible/ansible/issues/34196#issuecomment-371863179
    tags: always

#  roles:
#    - { role: vbmc-start }
